const data = {
  products: [
    {
      name: "Nike slim shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      images: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Adidas Fit shirt",
      slug: "adidas-fit-shirt",
      category: "Shirts",
      images: "/images/p2.jpg",
      price: 220,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      name: "Adidas slim pants",
      slug: "Adidas-slim-shirt",
      category: "pants",
      images: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
    {
      name: "Adidas slim pants",
      slug: "Adidas-slim-pants",
      category: "pants",
      images: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality pants",
    },
  ],
};

export default data;
